### ISSUE TITLE
Traits not implemented and import conflicts

### ISSUE THREAD

**Issue by anynoise00** [katharostech/bevy_retro#10]
I tried adding this plugin to my project, but there is a conflict happening when using Color, I know I can resolve it by using the explicit import, but if this keeps happenning with other things it would be bad. And there are some errors of non-implemented traits as shown in the error:

```
error[E0659]: `Color` is ambiguous (glob import vs glob import in the same module)
  --> src\main.rs:42:31
   |
42 |             background_color: Color::new(0.2, 0.2, 0.2, 1.0),
   |                               ^^^^^ ambiguous name
   |
note: `Color` could refer to the enum imported here
  --> src\main.rs:1:5
   |
1  | use bevy::prelude::*;
   |     ^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Color` to disambiguate
note: `Color` could also refer to the struct imported here
  --> src\main.rs:2:5
   |
2  | use bevy_retro::prelude::*;
   |     ^^^^^^^^^^^^^^^^^^^^^^
   = help: consider adding an explicit import of `Color` to disambiguate

error[E0277]: the trait bound `bevy_retro::RetroPlugins: bevy::prelude::PluginGroup` is not satisfied
 --> src\main.rs:7:22
  |
7 |         .add_plugins(RetroPlugins)
  |                      ^^^^^^^^^^^^ the trait `bevy::prelude::PluginGroup` is not implemented for `bevy_retro::RetroPlugins`

error[E0599]: no variant or associated item named `new` found for enum `bevy::prelude::Color` in the current scope
  --> src\main.rs:42:38
   |
42 |             background_color: Color::new(0.2, 0.2, 0.2, 1.0),
   |                                      ^^^ variant or associated item not found in `bevy::prelude::Color`

error[E0277]: the trait bound `bevy_retro::prelude::CameraBundle: Bundle` is not satisfied
  --> src\main.rs:38:27
   |
38 |       commands.spawn_bundle(CameraBundle {
   |  ___________________________^
39 | |         camera: Camera {
40 | |             // Set our camera to have a fixed height and an auto-resized width
41 | |             size: CameraSize::FixedHeight(100),
...  |
46 | |         ..Default::default()
47 | |     });
   | |_____^ the trait `Bundle` is not implemented for `bevy_retro::prelude::CameraBundle`

error: aborting due to 4 previous errors
```

my cargo.toml dependecies looks like this:
```
[dependencies]
bevy = { version = "0.5.0", default-features = false }
heron = { version = "0.5.0", default-features = false, features = ["2d"] }
bevy_retro = { git = "https://github.com/katharostech/bevy_retro", branch = "master" }
```

I'm also very new with Rust and Bevy, so maybe I am doing something wrong?

**Comment by zicklag** [comment]
Hey there! That's not your fault, I just pushed a fix for Bevy Retro that makes it work with Bevy 0.5 by default.

Also, `bevy_retro`, because it uses a custom renderer, is incompatible with `heron`'s debug rendering features. Because the `2d` feature of `heron` automatically enables the `heron_debug` crate which is incompatible with `bevy_retro`, you have to modify your cargo toml depedencies slightly to make sure we don't include the `heron_debug` crate:

```toml
bevy = { version = "0.5.0", default-features = false }
heron = { version = "0.5.0", default-features = false }
heron_rapier = { version = "0.5.0", features = ["2d"] }
bevy_retro = { git = "https://github.com/katharostech/bevy_retro", branch = "master" }
```

After that, run `cargo update` and you should be good to go!

**Comment by anynoise00** [comment]
That solved it, thanks!
